py3 support for write_props_file()
Prior to this change, write_props_file() would crash on Python 3 because
we did not have a "iteritems" method.

  AttributeError: 'dict' object has no attribute 'iteritems'

Switch to the "items()" method instead.

Add unit tests for the write_props_file() method to ensure that this
works on Python 2 and 3.