KojiBuilder: initialize ClientSession with strings
krbV.Principal(name=...) requires a string, and raises TypeError if
the value is unicode:

  TypeError: Invalid type unicode for argument 1

The values we pass into KoijSession are unicode (coming from
ConfigParser). When we set up koji's ClientSession, make sure we're
using strings there.