handle simple int branches
Prior to this change, "ceph-2-rhel-7" would cause the following error

  File "bucko/__init__.py", line 46, in parse_ci_message
      (major, _) = version.split('.', 1)
  ValueError: need more than 1 value to unpack